CREATE TABLE mst_service_options (
	service_option_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	service_type varchar(255) NOT NULL,
	category varchar(255) NOT NULL,
	"option" varchar(255) NOT NULL,
	category_normalized varchar(255) NOT NULL,
	option_normalized varchar(255) NOT NULL,
	created_at timestamp(6) NOT NULL,
	updated_at timestamp(6) NOT NULL,
	CONSTRAINT pk_mst_service_options PRIMARY KEY (service_option_id)
);