CREATE TABLE mst_accessories (
	product_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	product_code varchar(255) NULL,
	manufacturer varchar(255) NULL,
	product_name varchar(255) NULL,
	product_name_normalized varchar(255) NULL,
	created_at timestamp(6) NOT NULL,
	updated_at timestamp(6) NOT NULL,
	CONSTRAINT pk_mst_accessories PRIMARY KEY (product_id),
	CONSTRAINT uq_mst_accessories_product_code UNIQUE (product_code)
);