-- Generated by the database client.
CREATE TABLE trn_bfs_entries (
	bfs_entry_id varchar(20) NOT NULL,
	approval_id varchar(10) NOT NULL,
	company_id varchar(10) NOT NULL,
	initial_rental_period smallint NOT NULL,
	billing_number varchar(12) NOT NULL,
	contractor_number varchar(12) NOT NULL,
	pic_name_contract varchar(100) NULL,
	pic_name_kana_contract varchar(100) NULL,
	dep_name_contract varchar(100) NULL,
	dep_name_delivery varchar(100) NULL,
	agency_code_1 varchar(54) NULL,
	agency_name varchar(2295) NULL,
	last_4_digit_display varchar(10) NULL,
	invoice_delivery_route varchar(10) NULL,
	accessory_fee_payment_method varchar(900) NULL,
	accessory_fee_billing_category varchar(900) NULL,
	accessory_fee_combined_type varchar(900) NULL,
	rental_used_start_date varchar(60) NULL,
	rental_used_period_months varchar(6) NULL,
	maximum_number_of_lines_applicable_to_the_special_agreement numeric(10,0) NULL,
	stakeholder_1 varchar(2295) NULL,
	stakeholder_2 varchar(2295) NULL,
	stakeholder_3 varchar(2295) NULL,
	stakeholder_4 varchar(2295) NULL,
	stakeholder_5 varchar(2295) NULL,
	stakeholder_6 varchar(2295) NULL,
	stakeholder_7 varchar(2295) NULL,
	stakeholder_8 varchar(2295) NULL,
	stakeholder_9 varchar(2295) NULL,
	stakeholder_10 varchar(2295) NULL,
	sales_representative varchar(2295) NULL,
	telephone_number varchar(39) NULL,
	department_name varchar(2133) NULL,
	identity_verification_implementer_code varchar(30) NULL,
	receptionist_code varchar(30) NULL,
	campaign json NOT NULL,
	options json NOT NULL,
	rental_options json NOT NULL,
	discount_devices json NOT NULL,
	discount_services json NOT NULL,
	accessories json NOT NULL,
	created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    PRIMARY KEY(bfs_entry_id),
    CONSTRAINT fk_trn_bfs_entries_approval_id FOREIGN key(approval_id) REFERENCES trn_approval_mobile(approval_id)
);
CREATE INDEX idx_trn_bfs_entries_approval_id ON public.trn_bfs_entries USING btree (approval_id);
CREATE INDEX idx_trn_bfs_entries_company_id ON public.trn_bfs_entries USING btree (company_id);
CREATE INDEX idx_trn_bfs_entries_agency_code_1 ON public.trn_bfs_entries USING btree (agency_code_1);
CREATE INDEX idx_trn_bfs_entries_billing_number ON public.trn_bfs_entries USING btree (billing_number);
CREATE INDEX idx_trn_bfs_entries_contractor_number ON public.trn_bfs_entries USING btree (contractor_number);
CREATE INDEX idx_trn_bfs_entries_created_at ON public.trn_bfs_entries USING btree (created_at);
COMMENT ON TABLE trn_bfs_entries IS 'BFSエントリ情報を管理するトランザクションテーブル';
COMMENT ON COLUMN trn_bfs_entries.bfs_entry_id IS 'エントリ番号';
COMMENT ON COLUMN trn_bfs_entries.approval_id IS '決裁番号';
COMMENT ON COLUMN trn_bfs_entries.company_id IS '統一企業コード';
COMMENT ON COLUMN trn_bfs_entries.initial_rental_period IS '初期レンタル期間';
COMMENT ON COLUMN trn_bfs_entries.billing_number IS '請求先番号';
COMMENT ON COLUMN trn_bfs_entries.contractor_number IS '契約者番号';
COMMENT ON COLUMN trn_bfs_entries.pic_name_contract IS '契約先_担当者名';
COMMENT ON COLUMN trn_bfs_entries.pic_name_kana_contract IS '契約先_担当者名カナ';
COMMENT ON COLUMN trn_bfs_entries.dep_name_contract IS '契約先_担当者部署';
COMMENT ON COLUMN trn_bfs_entries.dep_name_delivery IS '請求先_部門名';
COMMENT ON COLUMN trn_bfs_entries.agency_code_1 IS '取次店コード1';
COMMENT ON COLUMN trn_bfs_entries.agency_name IS '取次店名';
COMMENT ON COLUMN trn_bfs_entries.last_4_digit_display IS '下4桁表示: 選択肢[全桁表示 / 下4桁非表示]';
COMMENT ON COLUMN trn_bfs_entries.invoice_delivery_route IS '請求書送付: 選択肢[顧客直送]';
COMMENT ON COLUMN trn_bfs_entries.campaign IS 'キャンペーン';
COMMENT ON COLUMN trn_bfs_entries.options IS 'オプション_販売時';
COMMENT ON COLUMN trn_bfs_entries.rental_options IS 'オプション_レンタル時';
COMMENT ON COLUMN trn_bfs_entries.discount_devices IS '相対割引_端末';
COMMENT ON COLUMN trn_bfs_entries.discount_services IS '相対割引_その他サービス';
COMMENT ON COLUMN trn_bfs_entries.accessories IS '付属品';
COMMENT ON COLUMN trn_bfs_entries.accessory_fee_payment_method IS '付属品代金支払い方法';
COMMENT ON COLUMN trn_bfs_entries.accessory_fee_billing_category IS '付属品代金請求区分';
COMMENT ON COLUMN trn_bfs_entries.accessory_fee_combined_type IS '付属品通話料合算種別';
COMMENT ON COLUMN trn_bfs_entries.rental_used_start_date IS 'rental_中古_開始年月日';
COMMENT ON COLUMN trn_bfs_entries.rental_used_period_months IS 'rental_中古_期間_ヶ月';
COMMENT ON COLUMN trn_bfs_entries.maximum_number_of_lines_applicable_to_the_special_agreement IS '特約適用上限回線数';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_1 IS '関係者1';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_2 IS '関係者2';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_3 IS '関係者3';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_4 IS '関係者4';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_5 IS '関係者5';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_6 IS '関係者6';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_7 IS '関係者7';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_8 IS '関係者8';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_9 IS '関係者9';
COMMENT ON COLUMN trn_bfs_entries.stakeholder_10 IS '関係者10';
COMMENT ON COLUMN trn_bfs_entries.sales_representative IS '営業担当者';
COMMENT ON COLUMN trn_bfs_entries.telephone_number IS '電話番号';
COMMENT ON COLUMN trn_bfs_entries.department_name IS '部署名';
COMMENT ON COLUMN trn_bfs_entries.identity_verification_implementer_code IS '本人確認実施者コード';
COMMENT ON COLUMN trn_bfs_entries.receptionist_code IS '受付担当者コード';
COMMENT ON COLUMN trn_bfs_entries.created_at IS '作成日';
COMMENT ON COLUMN trn_bfs_entries.updated_at IS '更新日';
