CREATE TABLE trn_bfs_mobile_service_summary_accessories (
    entry_no character varying(18) NOT NULL,
    attach_sm_id character varying(12) NOT NULL,
    serial_attach_flg_nm character varying(765),
    itm_cd character varying(15),
    brand_nm character varying(600),
    itm_nm character varying(300),
    color1 character varying(300),
    num1 numeric(6, 0),
    color2 character varying(300),
    num2 numeric(6, 0),
    color3 character varying(300),
    num3 numeric(6, 0),
    color4 character varying(300),
    num4 numeric(6, 0),
    color5 character varying(300),
    num5 numeric(6, 0),
    base_price numeric(10, 0),
    offered_price numeric(10, 0),
    use_point numeric(6, 0),
    trade_price numeric(11, 0),
    linked_svcsm_id character varying(30),
    attach_reserve_base_price numeric(8, 0),
    regist_date character varying(20),
    update_date character varying(20),
    industrial_company_cd character varying(4),
    load_day character varying(8),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
