-- Generated by the database client.
CREATE TABLE trn_approval_mobile(
	approval_id varchar(10) NOT NULL,
	company_id varchar(10) NOT NULL,
	company_name varchar(100) NOT NULL,
	operation_type varchar(18) NOT NULL,
	approval_title text NOT NULL,
	name_pic varchar(100) NULL,
	phone_number_pic varchar(11) NULL,
	case_title text NOT NULL,
	case_description text NOT NULL,
	expected_contract_start_date date NULL,
	contract_period smallint NULL,
	auto_extension_flg varchar(2) NOT NULL,
	related_approval_ids character varying[],
	created_at timestamp without time zone NOT NULL,
	updated_at timestamp without time zone NOT NULL,
	CONSTRAINT pk_trn_approval_mobile PRIMARY KEY (approval_id)
);
CREATE INDEX idx_trn_approval_mobile_company_id ON public.trn_approval_mobile USING btree (company_id);
CREATE INDEX idx_trn_approval_mobile_expected_contract_start_date ON public.trn_approval_mobile USING btree (expected_contract_start_date);
CREATE INDEX idx_trn_approval_mobile_created_at ON public.trn_approval_mobile USING btree (created_at);
COMMENT ON TABLE trn_approval_mobile IS 'モバイル決裁情報を管理するトランザクションテーブル';
COMMENT ON COLUMN trn_approval_mobile.approval_id IS '決裁番号: LS+7桁の数字。計9桁';
COMMENT ON COLUMN trn_approval_mobile.company_id IS '統一企業コード';
COMMENT ON COLUMN trn_approval_mobile.company_name IS '企業名';
COMMENT ON COLUMN trn_approval_mobile.operation_type IS '提案種別: 追加新規, 新規などが入る';
COMMENT ON COLUMN trn_approval_mobile.approval_title IS '決裁件名';
COMMENT ON COLUMN trn_approval_mobile.name_pic IS '担当者名';
COMMENT ON COLUMN trn_approval_mobile.phone_number_pic IS '担当者電話番号';
COMMENT ON COLUMN trn_approval_mobile.case_title IS '案件名';
COMMENT ON COLUMN trn_approval_mobile.case_description IS '案件概要: COMPASSの案件概要①＋案件概要②をマージ';
COMMENT ON COLUMN trn_approval_mobile.expected_contract_start_date IS '契約開始予定日';
COMMENT ON COLUMN trn_approval_mobile.contract_period IS '契約期間（ヶ月）';
COMMENT ON COLUMN trn_approval_mobile.auto_extension_flg IS '自動更新有無: データ_mst_デコードを参照';
COMMENT ON COLUMN trn_approval_mobile.related_approval_ids IS '関連する決裁番号';
COMMENT ON COLUMN trn_approval_mobile.created_at IS '作成日';
COMMENT ON COLUMN trn_approval_mobile.updated_at IS '更新日';
