CREATE OR REPLACE PROCEDURE sp_init_tmp_mars_campaign()
LANGUAGE plpgsql AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS tmp_mars_campaign (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campaign_id VARCHAR(40),
    campaign_name VARCHAR(2400),
    description VARCHAR(1200),
    effective_start_date VARCHAR(16),
    effective_end_date VARCHAR(16),
    CONSTRAINT pk_tmp_mars_campaign PRIMARY KEY (id)
    );

    COMMENT ON TABLE tmp_mars_campaign IS 'MARSキャンペーン一時テーブル';
    COMMENT ON COLUMN tmp_mars_campaign.id IS 'ID';
    COMMENT ON COLUMN tmp_mars_campaign.campaign_id IS 'キャンペーンid';
    COMMENT ON COLUMN tmp_mars_campaign.campaign_name IS 'キャンペーン名称';
    COMMENT ON COLUMN tmp_mars_campaign.description IS '説明';
    COMMENT ON COLUMN tmp_mars_campaign.effective_start_date IS '有効開始日';
    COMMENT ON COLUMN tmp_mars_campaign.effective_end_date IS '有効終了日';

    TRUNCATE TABLE tmp_mars_campaign;
END;
$$;
