CREATE OR REPLACE PROCEDURE sp_init_tmp_mars_product()
LANGUAGE plpgsql AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS tmp_mars_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_code VARCHAR(40),
    effective_start_date VARCHAR(16),
    effective_start_time VARCHAR(12),
    effective_end_date VARCHAR(16),
    effective_end_time VARCHAR(12),
    product_official_name VARCHAR(1200),
    product_middle_category_official_name VARCHAR(1200),
    brand_official_name VARCHAR(1200),
    product_color_official_name VARCHAR(600),
    model_code VARCHAR(40),
    model_official_name VARCHAR(1200),
    imsi_type VARCHAR(4),
    imsi_type_official_name VARCHAR(1200),
    CONSTRAINT pk_tmp_mars_product PRIMARY KEY (id)
    );

    COMMENT ON TABLE tmp_mars_product IS 'MARS商品一時テーブル';
    COMMENT ON COLUMN tmp_mars_product.id IS 'ID';
    COMMENT ON COLUMN tmp_mars_product.product_code IS '商品コード';
    COMMENT ON COLUMN tmp_mars_product.effective_start_date IS '有効開始日';
    COMMENT ON COLUMN tmp_mars_product.effective_start_time IS '有効開始時間';
    COMMENT ON COLUMN tmp_mars_product.effective_end_date IS '有効終了日';
    COMMENT ON COLUMN tmp_mars_product.effective_end_time IS '有効終了時間';
    COMMENT ON COLUMN tmp_mars_product.product_official_name IS '商品正式名称';
    COMMENT ON COLUMN tmp_mars_product.product_middle_category_official_name IS '商品中分類正式名称';
    COMMENT ON COLUMN tmp_mars_product.brand_official_name IS 'ブランド正式名称';
    COMMENT ON COLUMN tmp_mars_product.product_color_official_name IS '商品色正式名称';
    COMMENT ON COLUMN tmp_mars_product.model_code IS '機種コード';
    COMMENT ON COLUMN tmp_mars_product.model_official_name IS '機種正式名称';
    COMMENT ON COLUMN tmp_mars_product.imsi_type IS 'imsiタイプ';
    COMMENT ON COLUMN tmp_mars_product.imsi_type_official_name IS 'imsiタイプ正式名称';

    TRUNCATE TABLE tmp_mars_product;
END;
$$;
