CREATE OR REPLACE PROCEDURE sp_init_tmp_mars_product()
LANGUAGE plpgsql AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS tmp_mars_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    itm_cd VARCHAR(20),
    effective_dt_from VARCHAR(8),
    effective_tm_from VARCHAR(6),
    effective_dt_to VARCHAR(8),
    effective_tm_to VARCHAR(6),
    long_nm VARCHAR(600),
    itm_lvl2_id VARCHAR(10),
    lvl2_long_nm VARCHAR(600),
    brand_long_nm VARCHAR(600),
    color_nm VARCHAR(300),
    model_cd VARCHAR(20),
    model_long_nm VARCHAR(600),
    ins_itm_typ_cd VARCHAR(3),
    imsi_typ VARCHAR(2),
    imsi_typ_nm VARCHAR(600),
    CONSTRAINT pk_tmp_mars_product PRIMARY KEY (itm_cd, effective_dt_from, effective_tm_from)
    );

    COMMENT ON TABLE tmp_mars_product IS 'MARS商品一時テーブル';
    COMMENT ON COLUMN tmp_mars_product.id IS 'ID';
    COMMENT ON COLUMN tmp_mars_product.itm_cd IS '商品コード';
    COMMENT ON COLUMN tmp_mars_product.effective_dt_from IS '有効開始日';
    COMMENT ON COLUMN tmp_mars_product.effective_tm_from IS '有効開始時間';
    COMMENT ON COLUMN tmp_mars_product.effective_dt_to IS '有効終了日';
    COMMENT ON COLUMN tmp_mars_product.effective_tm_to IS '有効終了時間';
    COMMENT ON COLUMN tmp_mars_product.long_nm IS '商品正式名称';
    COMMENT ON COLUMN tmp_mars_product.itm_lvl2_id IS '商品中分類ID';
    COMMENT ON COLUMN tmp_mars_product.lvl2_long_nm IS '商品中分類正式名称';
    COMMENT ON COLUMN tmp_mars_product.brand_long_nm IS 'ブランド正式名称';
    COMMENT ON COLUMN tmp_mars_product.color_nm IS '商品色正式名称';
    COMMENT ON COLUMN tmp_mars_product.model_cd IS '機種コード';
    COMMENT ON COLUMN tmp_mars_product.model_long_nm IS '機種正式名称';
    COMMENT ON COLUMN tmp_mars_product.ins_itm_typ_cd IS '検品用商品タイプコード';
    COMMENT ON COLUMN tmp_mars_product.imsi_typ IS 'IMSIタイプ';
    COMMENT ON COLUMN tmp_mars_product.imsi_typ_nm IS 'IMSIタイプ名称';

    TRUNCATE TABLE tmp_mars_product;
END;
$$;
