CREATE OR REPLACE PROCEDURE sp_init_tmp_corp_customer_info()
LANGUAGE plpgsql AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS tmp_diff_corp_customer_info (
    company_id TEXT,
    willcom_company_id TEXT,
    dans_number TEXT,
    corporate_structure_code TEXT,
    company_name_kana_hw TEXT,
    company_name_kana TEXT,
    company_name TEXT,
    company_name_kana_hw_for_search TEXT,
    company_name_kana_for_search TEXT,
    company_name_for_search TEXT,
    postal_code TEXT,
    addresses TEXT,
    addresses_prefecture TEXT,
    addresses_city TEXT,
    addresses_line1 TEXT,
    addresses_line2 TEXT,
    addresses_building TEXT,
    phone_number TEXT,
    main_biz_code TEXT,
    sub_biz_code TEXT,
    job_title TEXT,
    ceo_name_kana_hw TEXT,
    ceo_name_kana TEXT,
    ceo_name TEXT,
    main_biz TEXT,
    sub_biz TEXT,
    organizational_div TEXT,
    contents_of_biz TEXT,
    degree_of_importance TEXT,
    sec_code TEXT,
    company_url TEXT,
    marged_company_id TEXT,
    parent_enterprise_flg TEXT,
    parent_enterprise_id TEXT,
    sb_category TEXT,
    sb_subcategory TEXT,
    sb_subusubcategory TEXT,
    notes1 TEXT,
    notes2 TEXT,
    notes3 TEXT,
    notes4 TEXT,
    notes5 TEXT,
    valid_flg TEXT,
    invalid_reason TEXT,
    registerd_at TEXT,
    updated_at TEXT,
    registered_by TEXT,
    updated_by TEXT,
    del_flg TEXT,
    summit_registerd_at TEXT,
    summit_updated_at TEXT,
    summit_registerd_by TEXT,
    summit_updated_by TEXT,
    data_universal_number TEXT,
    mnc_management_name TEXT,
    postal_code_2 TEXT,
    country_code TEXT,
    city TEXT,
    country_calling_code TEXT,
    district TEXT,
    local_company_name_ja TEXT,
    customer_name TEXT,
    notes6 TEXT
    );
    TRUNCATE TABLE tmp_diff_corp_customer_info;
END;
$$;
