CREATE OR REPLACE PROCEDURE sp_init_tmp_mars_agency()
LANGUAGE plpgsql AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS tmp_diff_mars_agency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    agency_code VARCHAR(40),
    effective_start_date VARCHAR(16),
    effective_end_date VARCHAR(16),
    agency_name VARCHAR(1200),
    updated_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tmp_diff_mars_agency PRIMARY KEY (id)
    );

    COMMENT ON TABLE tmp_diff_mars_agency IS 'MARS取次店一時テーブル';
    COMMENT ON COLUMN tmp_diff_mars_agency.id IS 'ID';
    COMMENT ON COLUMN tmp_diff_mars_agency.agency_code IS '取次店コード';
    COMMENT ON COLUMN tmp_diff_mars_agency.effective_start_date IS '有効開始日';
    COMMENT ON COLUMN tmp_diff_mars_agency.effective_end_date IS '有効終了日';
    COMMENT ON COLUMN tmp_diff_mars_agency.agency_name IS '取次店正式名称';
    COMMENT ON COLUMN tmp_diff_mars_agency.updated_at IS '更新日時';

    TRUNCATE TABLE tmp_diff_mars_agency;
END;
$$;
